name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make
    - name: Create build directory
      run: mkdir build
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++
    - name: Build
      run: cmake --build build

